config/routes.rb
Rails.application.routes.draw do

  # ROOT
  root 'home#index'

  # Registration Devise Route
  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}

  # Home Routes
  get 'home/index'
  get 'welcome/index'

  # Search Routes
  get 'search', to: 'search#search', as: 'search'
  get 'job_types/index', to: 'job_types#index', as: 'job_types'
  # JOB Routes
  resources :jobs
  resources :job_types
  resources :offer_jobs
  resources :apply_jobs
  resources :accept_jobs
  resources :cancel_jobs
  resources :finished_jobs
  get 'my_finished_jobs', to: 'finished_jobs#my_finished_jobs'
  get 'job/clientjobs', to: 'jobs#clientjobs', as: 'clientjobs'
  get 'job/:id/recommended_teens', to: 'jobs#recommended_teens', as: 'recommended_teens'
  get 'profile/:user_id', to: 'profiles#this_profile', as: 'this_profile'

  resources :charges
  resources :admin, only: [:index]

  # Routes
  resources :users, only: [:index, :show, :destroy] do
    resources :transactions
    resources :clients, only: [:show, :edit, :update]
    resources :endorsements, only: [:create, :update, :destroy]
    resources :teenagers, :name_prefix => "user_", only: [:show, :edit, :update]

	  get 'payments/index', to: 'payments#index', as: 'paymentsindex'

    member do
         post :pay
         post :subscribe
    end
  end

  resources :teenagers do
    resources :skills, :name_prefix => "teenager_"
  end

  get '/users/connect_stripe' => 'users#connect_stripe' 

  # Stripe Connect endpoints
  #  - oauth flow
  get '/connect/oauth' => 'stripe#oauth', as: 'stripe_oauth'
  get '/connect/confirm' => 'stripe#confirm', as: 'stripe_confirm'
  get '/connect/deauthorize' => 'stripe#deauthorize', as: 'stripe_deauthorize'
  #  - create accounts
  post '/connect/managed' => 'stripe#managed', as: 'stripe_managed'
  post '/connect/standalone' => 'stripe#standalone', as: 'stripe_standalone'

  # Stripe webhooks
  post '/hooks/stripe' => 'hooks#stripe'
end

app/views/template/nav/_defaultmenu.html.erb
<br><br>
<!-- Default Menu bar -->
<nav class="navbar navbar-inverse navbar-fixed-bottom">
    <div class="container-fluid">
      <div class="row">
          

        <div class="col-lg-2 col-md-2 col-sm-18 col-xs-18">   
          <span class="nav_link" style="float:right">
            <%= link_to(new_user_session_path) do %><i class="fa fa-sign-in"></i><% end %>
          </span>
          <span class="nav_link" style="float:left">
            <%= link_to(new_user_registration_path) do %><i class="fa fa-plus"></i><% end %>
          </span>
        </div>
        <div class="col-lg-7 col-md-7 hidden-sm hidden-xs">
            <%= form_tag(search_path, method: "get", class: "navbar-form", style: "float:right") do %>
                <%= text_field_tag :q, params[:q], placeholder: "Search", class: "form-control", style: "width:500px;" %>
                <%= button_tag(type: "submit", class: "btn btn-default") do %>
                  <span class="fa fa-search"></span>
                <% end %>
            <% end %>
        </div>
        <div class="col-lg-3 col-md-3 hidden-sm hidden-xs">
          <ul class="nav navbar-nav navbar-right" style="float:right">
              <li><%= link_to(welcome_index_path) do %><span class="fa fa-info-circle"></span> About Us</a></li><% end %>
          </ul>
      </div>
      </div>
  </div>
</nav>

app/views/template/nav/_usermenu.html.erb
<br><br>
<!-- Nav bar -->
<nav class="navbar navbar-inverse navbar-fixed-bottom">
    <div class="container-fluid">
      <div class="row">

      <div class="col-lg-2 col-md-2 col-sm-18 col-xs-18">
          <span class="nav_trigger" style="float:left">
              <i class="fa fa-user"></i>
          </span>
        </div>
        <% if @user.usertype != 2 %>
        <div class="col-lg-7 col-md-7 hidden-sm hidden-xs">
            <%= form_tag(search_path, method: "get", class: "navbar-form", style: "float:right") do %>
                <%= text_field_tag :q, params[:q], placeholder: "Search", class: "form-control", style: "width:500px;" %>
                <%= button_tag(type: "submit", class: "btn btn-default") do %>
                  <span class="fa fa-search"></span>
                <% end %>
            <% end %>
        </div>
        
        <div class="col-lg-3 col-md-3 hidden-sm hidden-xs">
          <ul class="nav navbar-nav navbar-right" style="float:right">
              <li><%= link_to(welcome_index_path) do %><span class="fa fa-info-circle"></span> About Us</li><% end %>
          </ul>
      </div>
      <% end %>
      </div>
  </div>
</nav>
<!-- ./bottom menu bar -->
<!-- Sidebar -->
<div id="push_sidebar">
  <h6>Status: <% if @user.usertype ==0 %>Teenager<% elsif @user.usertype==1 %>Client<% else %>Admin<% end %></h6>
<h2> Signed in as <%= @user.username %> </h2>
  <ul class="list-unstyled">
    <li><a href="/"><span class="fa fa-home"></span>Home</a></li>


    <% if(current_user.usertype==0) %>
      <% @teenager = Teenager.find_by_user_id(current_user.id) %>
        <li><%= link_to(jobs_path) do %><span class="fa fa-list-ul"></span>Jobs<% end %></li>
        <li><%= link_to(user_teenager_path(current_user.id, @teenager.id)) do %><span class="fa fa-id-card"></span>Profile<% end %></li>
        <li><%= link_to(edit_user_teenager_path(current_user.id, @teenager.id)) do %><span class="fa fa-pencil"></span>Update Account Information<% end %></li>
        <li><%= link_to(user_transactions_path(current_user.id, @teenager.id)) do %><span class="fa fa-credit-card"></span>Transaction History<% end %></li>

    <% elsif(current_user.usertype==1) %>

      <% @client = Client.find_by_user_id(current_user.id) %>
        <li><%= link_to(jobs_path) do %><span class="fa fa-list-ul"></span>Jobs<% end %></li>
        <li><%= link_to(user_client_path(current_user.id, @client.id)) do %><span class="fa fa-id-card"></span>Profile<% end %></li>
        <li><%= link_to(edit_user_client_path(current_user.id, @client.id)) do %><span class="fa fa-pencil"></span>Update Account Information<% end %></li>
        <li><%= link_to(accept_jobs_path) do %><span class="fa  glyphicon-exclamation-sign"></span>All Teenager Applicants<% end %></li>

        <li><%= link_to(my_finished_jobs_path) do %><span class="fa fa-credit-card"></span>My Finished Jobs<% end %></li>
        <li><%= link_to(finished_jobs_path) do %><span class="fa fa-credit-card"></span>Ready to Finish<% end %></li>

        <li><%= link_to(user_transactions_path(current_user.id, @client.id)) do %><span class="fa fa-credit-card"></span>Transaction History<% end %></li>

      <li><%= link_to(new_job_path) do %><span class="fa fa-plus"></span>Post New Job<% end %></li>

    <% else %>
      <li><%= link_to(admin_index_url) do %><span class="fa fa-list-ul"></span>Admin Console<% end %></li>

    <% end %>
    <li><%= link_to(destroy_user_session_path, method: :delete) do %><span class="fa fa-power-off"></span>Log Out<% end %></li>
  </ul>
</div>