config/routes.rb
Rails.application.routes.draw do

  # ROOT
  root 'home#index'

  # Registration Devise Route
  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}

  # Home Routes
  get 'home/index'
  get 'welcome/index'

  # Search Routes
  get 'search', to: 'search#search', as: 'search'
  get 'job_types/index', to: 'job_types#index', as: 'job_types'
  # JOB Routes
  resources :jobs
  resources :job_types
  resources :offer_jobs
  resources :apply_jobs
  resources :accept_jobs
  resources :cancel_jobs
  resources :finished_jobs
  get 'my_finished_jobs', to: 'finished_jobs#my_finished_jobs'
  get 'job/clientjobs', to: 'jobs#clientjobs', as: 'clientjobs'
  get 'job/:id/recommended_teens', to: 'jobs#recommended_teens', as: 'recommended_teens'
  get 'profile/:user_id', to: 'profiles#this_profile', as: 'this_profile'

  resources :charges
  resources :admin, only: [:index]

  # Routes
  resources :users, only: [:index, :show, :destroy] do
    resources :transactions
    resources :clients, only: [:show, :edit, :update]
    resources :endorsements, only: [:create, :update, :destroy]
    resources :teenagers, :name_prefix => "user_", only: [:show, :edit, :update]

	  get 'payments/index', to: 'payments#index', as: 'paymentsindex'

    member do
         post :pay
         post :subscribe
    end
  end

  resources :teenagers do
    resources :skills, :name_prefix => "teenager_"
  end

  get '/users/connect_stripe' => 'users#connect_stripe' 

  # Stripe Connect endpoints
  #  - oauth flow
  get '/connect/oauth' => 'stripe#oauth', as: 'stripe_oauth'
  get '/connect/confirm' => 'stripe#confirm', as: 'stripe_confirm'
  get '/connect/deauthorize' => 'stripe#deauthorize', as: 'stripe_deauthorize'
  #  - create accounts
  post '/connect/managed' => 'stripe#managed', as: 'stripe_managed'
  post '/connect/standalone' => 'stripe#standalone', as: 'stripe_standalone'

  # Stripe webhooks
  post '/hooks/stripe' => 'hooks#stripe'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
 	
 	before_action :user_assertion_profile, only: [:this_profile]
 	before_action :self_assertion_profile, only: [:this_profile]

	def this_profile
		@this_user = User.find(params[:user_id])



		@user = current_user

	    if @this_user.usertype == 0 #Teenager
	      	@this_teenager = Teenager.find_by(user_id: @this_user.id)
	      	@endorsements = Endorsement.where(end_user_id: @this_user.id, removed: 0).all
	      	if @endorsements
	      		@end_count = @endorsements.count
	      	end
	      	@jobs = Job.where(teenager_id: @this_teenager.id).order("created_at DESC").limit(3)
        	@rating_coll = Job.where("teenager_id = ? AND cancelled = ? AND finished = ?", @this_teenager.id, false, true)
	        # ratings matter only for finished jobs
	        @r_count = @rating_coll.count
	        @r_avg = @rating_coll.average(:teens_rating)
        	if @this_teenager.nil?
	      		redirect_to home_index_url
	      	else
	      		@endorsement = Endorsement.find_by(ref_user_id: @user.id, end_user_id: @this_user.id)
	      		if @endorsement.nil?
					@new_endorsement = @this_user.g_endorsement.new
	      		end
	      		render "profiles/show_teenager"
	    	end
	    
	    elsif @this_user.usertype == 1 #Client
	    	@this_client = Client.find_by(user_id: @this_user.id)
	      	@jobs = Job.where(client_id: @this_client.id).order("created_at DESC").limit(3)
    		@rating_coll = Job.where("client_id = ? AND cancelled = ? AND finished = ?", @this_client.id, false, true)
			# ratings matter only for finished jobs
			@r_count = @rating_coll.count
			@r_avg = @rating_coll.average(:clients_rating)
    		if @this_client.nil?
	      		redirect_to home_index_url
	      	else
	      		render "profiles/show_client"
	  		end
	  	else
	  		redirect_to home_index_url
	    end
	end
	
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/template/profile/OLD_client_profile.html.erb
<body>

<div class="section">
	<div class="container" style="padding-top:55px;">
			<div class="row">
				<div class="col-md-4">
	    	 		<div class="well profile">
	            		<div class="col-md-12">
	                  		<div class="col-md-4 text-center">
	                    		<figure>
	                        		<img src="https://res.cloudinary.com/closebrace/image/upload/w_400/v1491315007/usericon_id76rb.png" alt="" class="img-circle img-responsive">
	                    		</figure>
	                  		</div>

	             		   <div class="col-md-8 text-right">
	             		   		<div class = "box">
									<h1>Your details:</h1>
									<p><strong>Username:</strong><%= @user.username %></p>
									<p> Usertype: Client </p>
									<p>Name: <%= @client.fName %> <%= @client.lName %></p>
									<p>Gender: <%= @client.gender%></p>
									<p>Birthday (mm/dd/yyyy): <%= @client.birth_month %>/<%= @client.birth_day %>/<%= @client.birth_year %></p>
									<p>Address: <%= @client.address%></p>
									<p>Apartment number: <%= @client.apt_no%></p>
									<p>City: <%= @client.city%></p>
									<p>Province: <%= @client.province%></p>
									<p>Country: <%= @client.country%></p>
									<p>Postal Code: <%= @client.postal_code%></p>
								</div>
	                		</div>             
	            		</div>            
	            	<div class="col-md-12 divider text-center">
	            	<row>
	                	<div class="col-md-3 emphasis">
	                    	<button class="btn btn-success btn-block"><span class="fa fa-plus-circle"></span>New payment</button>
	               		</div>
	               		<div class="col-md-3 emphasis">
	                    	<button class="btn btn-success btn-block"><span class="fa fa-plus-circle"></span>New endorsement</button>
	               		</div>
	                <!-- if needed as a spacer <div class="col-md-2"></div> -->
	               	<div class="col-md-2 emphasis">
		               	<%= link_to(new_job_path) do %>
		                	<button class="btn btn-info btn-block"><span class="fa fa-plus"></span>New Job</button>
		                <% end %>
		            </div>
	                <div class="col-md-2 emphasis">
	                    <button class="btn btn-info btn-block"><span class="fa fa-gear"></span>Manage Jobs</button>
	                </div>
	                <div class="col-md-2 emphasis">
	                    <%= link_to(edit_user_client_path(@user.id, @client.id)) do %>
	                    	<button type="button" class="btn btn-info btn-block"><span class="fa fa-gear"></span>Edit Profile</button>
	                    <% end %>
	                </div>
	            </row>
	            

	            <row>
	                <div class="section">
	                    <div class="padding-top">

	                    <!-- Ongoing Jobs -->
	                        <div class="col-md-12">
	                          <div class="panel-group" id="accordion">
	                              <div class="panel panel-primary">
	                                  <div class="panel-heading">
	                                    <h4 class="panel-title">
	                                      <a href="#collpase1" data-toggle="collapse" data-parent="accordion">Ongoing Jobs</a>
	                                    </h4>
	                                </div>
	                                  <div id="collpase1" class="panel-collapse collapse in">
	                                    <div class="panel-body">
	                                        <section class="align-box">
	                                      </section>
	                                    </div>
	                                  </div>
	                              </div>
	                          </div>
	                        </div>
	                        <!-- end -->

	                        <!-- Recently completed Jobs -->
	                        <div class="col-md-12">
	                          	<div class="panel-group" id="accordion">
	                              	<div class="panel panel-primary">
	                                  	<div class="panel-heading">
	                                    	<h4 class="panel-title">
	                                      		<a href="#collpase2" data-toggle="collapse" data-parent="accordion">Recent Jobs</a>
	                                    	</h4>
	                                	</div>
	                                	<div id="collpase2" class="panel-collapse collapse in">
	                                    	<div class="panel-body">
	                                        	<section class="align-box">
	                                      		</section>
	                                    	</div>
	                                  	</div>
	                              	</div>
	                          	</div>
	                        </div>
	                        <!-- end -->


	                   	<!-- enclosing tags -->
	                	</div>
	              	</div>
	            </row>
	            </div>
	    	 </div>                 
			</div>
		</div>
	</div>
</div>
<!-- enclosing tags -->

app/views/template/profile/OLD_teen_profile.html.erb
<body>

<div class="section">
	<div class="container" style="padding-top:55px;">
			<div class="row">
				<div class="col-md-4">
	    	 		<div class="well profile">
	            		<div class="col-md-12">
	                  		<div class="col-md-4 text-center">
	                    		<figure>
	                        		<img src="https://res.cloudinary.com/closebrace/image/upload/w_400/v1491315007/usericon_id76rb.png" alt="" class="img-circle img-responsive">
	                    		</figure>
	                  		</div>

	             		   <div class="col-md-8 text-right">
	             		   		<div class = "box">
									<h1>Your details:</h1>
									<p><strong>Username:</strong><%= @user.username %></p>
									<p> Usertype: Teenager </p>
									<p>Name: <%= @client.fName %> <%= @client.lName %></p>
									<p>Gender: <%= @client.gender%></p>
									<p>Birthday (mm/dd/yyyy): <%= @client.birth_month %>/<%= @client.birth_day %>/<%= @client.birth_year %></p>
									<p>Address: <%= @client.address%></p>
									<p>Apartment number: <%= @client.apt_no%></p>
									<p>City: <%= @client.city%></p>
									<p>Province: <%= @client.province%></p>
									<p>Country: <%= @client.country%></p>
									<p>Postal Code: <%= @client.postal_code%></p>
								</div>
	                		</div>             
	            		</div>            
	            	<div class="col-md-12 divider text-center">
	            	<row>
	                	<div class="col-md-3 emphasis">
	                    	<button class="btn btn-success btn-block"><span class="fa fa-plus-circle"></span>New payment</button>
	               		</div>
	               		<div class="col-md-3 emphasis">
	                    	<button class="btn btn-success btn-block"><span class="fa fa-plus-circle"></span>New endorsement</button>
	               		</div>
	                <!-- if needed as a spacer <div class="col-md-2"></div> -->
	               	<div class="col-md-2 emphasis">
		               	<%= link_to(new_job_path) do %>
		                	<button class="btn btn-info btn-block"><span class="fa fa-plus"></span>New Job</button>
		                <% end %>
		            </div>
	                <div class="col-md-2 emphasis">
	                    <button class="btn btn-info btn-block"><span class="fa fa-gear"></span>Manage Jobs</button>
	                </div>
	                <div class="col-md-2 emphasis">
	                    <%= link_to(edit_user_client_path(@user.id, @client.id)) do %>
	                    	<button type="button" class="btn btn-info btn-block"><span class="fa fa-gear"></span>Edit Profile</button>
	                    <% end %>
	                </div>
	            </row>
	            

	            <row>
	                <div class="section">
	                    <div class="padding-top">

	                    <!-- Ongoing Jobs -->
	                        <div class="col-md-12">
	                          <div class="panel-group" id="accordion">
	                              <div class="panel panel-primary">
	                                  <div class="panel-heading">
	                                    <h4 class="panel-title">
	                                      <a href="#collpase1" data-toggle="collapse" data-parent="accordion">Ongoing Jobs</a>
	                                    </h4>
	                                </div>
	                                  <div id="collpase1" class="panel-collapse collapse in">
	                                    <div class="panel-body">
	                                        <section class="align-box">
	                                      </section>
	                                    </div>
	                                  </div>
	                              </div>
	                          </div>
	                        </div>
	                        <!-- end -->

	                        <!-- Recently completed Jobs -->
	                        <div class="col-md-12">
	                          	<div class="panel-group" id="accordion">
	                              	<div class="panel panel-primary">
	                                  	<div class="panel-heading">
	                                    	<h4 class="panel-title">
	                                      		<a href="#collpase2" data-toggle="collapse" data-parent="accordion">Recent Jobs</a>
	                                    	</h4>
	                                	</div>
	                                	<div id="collpase2" class="panel-collapse collapse in">
	                                    	<div class="panel-body">
	                                        	<section class="align-box">
	                                      		</section>
	                                    	</div>
	                                  	</div>
	                              	</div>
	                          	</div>
	                        </div>
	                        <!-- end -->


	                   	<!-- enclosing tags -->
	                	</div>
	              	</div>
	            </row>
	            </div>
	    	 </div>                 
			</div>
		</div>
	</div>
</div>
<!-- enclosing tags -->

app/views/template/profile/_client_edit_form.html.erb
<div class="box">

<%= form_with(model: [@user, @user.client], local: true) do |form| %>
 
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@client.errors.count, "error") %> prohibited
        this client form from being saved:
      </h2>
      <ul>
        <% @client.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<h1>Edit Your Profile</h1>

 <div class="col-half">
  <p>
    <%= form.label :'First Name:' %>
    <%= form.text_field :fName %>
  </p>
</div>
<div class="col-half">
  <p>
    <%= form.label :'Last Name:' %>
    <%= form.text_field :lName %>
  </p>
</div>
  <div class="row">
  <div class="col-half">
  <p>
  <h3>
    <%= form.label :'Gender:' %>
	</h3>
    <%= form.select :gender, [['Male', 'male'], ['Female', 'female'],['Bi', 'bi']] %>
 
  </p>
  </div>
</div>
  <h3>Date of Birth</h3>
  <p>
  <div class="col-third">
    <%= form.label :'Month' %>
    <%= form.text_field :birth_month %>
	</div>
	<div class="col-third">
    <%= form.label :'Day' %>
    <%= form.text_field :birth_day %>
	</div>
	<div class="col-third">
    <%= form.label :'Year' %>
    <%= form.text_field :birth_year %>
	</div>
  </p>

  <h3>Address</h3>
    <p>
    <%= form.label :'Address Line' %>
    <%= form.text_field :address %>
  </p>
  <p>
    <%= form.label :'Apt.No' %>
    <%= form.text_field :apt_no %>
  </p>
    <p>
    <%= form.label :'City' %>
    <%= form.text_field :city %>
  </p>
  <div class="col-half">
  <p>
    <%= form.label :'Province/State' %>
    <%= form.text_field :province %>
  </p>
  </div>
  <div class="col-half">
  <p>
    <%= form.label :'Country' %>
    <%= form.text_field :country %>
  </p>
  </div>
  <p>
    <%= form.label :'Postal Code' %>
    <%= form.text_field :postal_code %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

</div>

app/views/template/profile/_client_profile.html.erb
<div class="mainbody container-fluid">
    <div class="row">

        <div style="padding-top:2px;"> </div>

        <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h1 class="panel-title pull-left" style="font-size:40px;"><%= @client.fName %> <%= @client.lName %>
                        <small>(<%= @user.username %>)</small>
                    </h1>
                    <span class="pull-right">
                        <div class="well well-sm">
                            <div class="row">
                                <div class="col-xs-18 col-md-12 text-center">
                                  <% if(@r_count == 0) %>
                                    <div class="rating">
                                        No ratings
                                    </div>
                                  <% else %>
                                    <h1 class="rating-num">
                                        <%= @r_avg %></h1>
                                    <div class="rating">
                                      <% case @r_avg %>
                                      <% when 0..0.5 %>
                                        <span class="glyphicon glyphicon-star-empty"></span>
                                        <span class="glyphicon glyphicon-star-empty"></span>
                                        <span class="glyphicon glyphicon-star-empty"></span>
                                        <span class="glyphicon glyphicon-star-empty"></span>
                                        <span class="glyphicon glyphicon-star-empty"></span>
                                      <% when 0.5..1.5 %>
                                        <span class="glyphicon glyphicon-star"></span>
                                        <span class="glyphicon glyphicon-star-empty"></span>
                                        <span class="glyphicon glyphicon-star-empty"></span>
                                        <span class="glyphicon glyphicon-star-empty"></span>
                                        <span class="glyphicon glyphicon-star-empty"></span>
                                      <% when 1.5..2.5 %>
                                      <span class="glyphicon glyphicon-star"></span>
                                        <span class="glyphicon glyphicon-star"></span>
                                        <span class="glyphicon glyphicon-star-empty"></span>
                                        <span class="glyphicon glyphicon-star-empty"></span>
                                        <span class="glyphicon glyphicon-star-empty"></span>
                                      <% when 2.5..3.5 %>
                                        <span class="glyphicon glyphicon-star"></span>
                                        <span class="glyphicon glyphicon-star"></span>
                                        <span class="glyphicon glyphicon-star"></span>
                                        <span class="glyphicon glyphicon-star-empty"></span>
                                        <span class="glyphicon glyphicon-star-empty"></span>
                                      <% when 3.5..4.5 %>
                                        <span class="glyphicon glyphicon-star"></span>
                                        <span class="glyphicon glyphicon-star"></span>
                                        <span class="glyphicon glyphicon-star"></span>
                                        <span class="glyphicon glyphicon-star"></span>
                                        <span class="glyphicon glyphicon-star-empty"></span>
                                      <% when 4.5..5 %>
                                        <span class="glyphicon glyphicon-star"></span>
                                        <span class="glyphicon glyphicon-star"></span>
                                        <span class="glyphicon glyphicon-star"></span>
                                        <span class="glyphicon glyphicon-star"></span>
                                        <span class="glyphicon glyphicon-star"></span>
                                      <% end %>
                                    </div>
                                    <div>
                                        <span class="glyphicon glyphicon-user"></span> <%= @r_count %> total
                                    </div>
                                  <% end %>
                                </div>
                            </div>
                        </div>

                    </span>
                    <br><br><br><br><br><br>
                    <span class="pull-left">
                       <div class="btn btn-link" style="text-decoration:none;"><i class="fa fa-credit-card" aria-hidden="true"></i>
                        <%= link_to("Payment Info", controller:"users", action:"show", id:@current_user) %>
                      </div>
                    </span>
                </div>
            </div>
            <hr>


            <!-- Upcoming Jobs -->
            <div class="panel panel-default">
                <span class="pull-right">
                    <div class="btn btn-link" style="text-decoration:none;">
                        <%= link_to(clientjobs_path(@client.id)) do %>
                            <i class="fa fa-address-card-o" aria-hidden="true" data-toggle="tooltip" data-placement="bottom"></i>
                        <% end %>
                    </div>
                </span>
                <div class="panel-body">
                    <h4><strong>Upcoming Jobs</strong></h4>

                    <hr>
                    <div class="post-content">
                        <% if @jobs %>
                            <% @jobs.each do |job| %>
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-6">
                                    <div class="panel panel-default">
                                        <div class="panel-body">
                                            <h4>
                                              <strong><%= JobType.find(job.job_type_id).name %></strong><br/>
                                              <small><small><i><i class="fa fa-clock-o" aria-hidden="true"></i> <%= job.starttime %></i></small></small>
                                            </h4>
                                            <hr>
                                            <div class="post-content">
                                                <%= job.description %>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            </div>

            <!-- Recent Transactions -->
            <div class="panel panel-default">
                <span class="pull-right">
                    <div class="btn btn-link" style="text-decoration:none;">
                        <%= link_to(user_transactions_path(current_user.id, @client.id)) do %>
                            <i class="fa fa-credit-card" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="Mention"></i>
                        <% end %>
                    </div>
                </span>
                <div class="panel-body">
                    <% if @transactions.nil? %>
                      <h4><strong>Recent Transactions</strong></h4>
                      <hr>
                      <p>No transactions found</p>
                    <% elsif Array(@transactions).count == 0 %>
                      <h4><strong>Recent Transactions</strong></h4>
                      <hr>
                      <p>No transactions found</p>
                    <% else %>
                      <% recent_trans = Array(@transactions).first %>
                      <% recent_trans_date = recent_trans.trans_date %>
                      <% currentUTC = Time.now.utc %>
                      <% diff_in_months = (currentUTC.year*12 + currentUTC.month) - (recent_trans_date.year*12 + recent_trans_date.month) %>
                      <% diff_in_days = currentUTC.mday - recent_trans_date.mday %>
                      <% if diff_in_days < 0 %>
                        <% diff_in_months -= 1 %>
                        <% diff_in_days += 30 %>
                      <% end %>
                      <% diff_in_hrs = currentUTC.hour - recent_trans_date.hour %>
                      <% if diff_in_hrs < 0 %>
                        <% diff_in_days -= 1 %>
                        <% diff_in_hrs += 24 %>
                      <% end %>
                      <% diff_in_time = "" %>
                      <% if diff_in_months > 0 %>
                        <% diff_in_time += diff_in_months.to_s + " months " %>
                      <% end %>
                      <% if diff_in_days > 0 %>
                        <% diff_in_time += diff_in_days.to_s + " days " %>
                      <% end %>
                      <% if diff_in_hrs > 0 %>
                        <% diff_in_time += diff_in_hrs.to_s + " hours " %>
                      <% end %>
                      <% diff_in_time += " ago" %>
                      <h4>
                        <strong>Recent Transactions</strong> – <small><small><i><i class="fa fa-clock-o" aria-hidden="true"></i> <%= diff_in_time %></i></small></small>
                      </h4>
                      <hr>
                      <% Array(@transactions).each do |transaction| %>
                        <div class="post-content">
                            <strong><%= JobType.find(transaction.job.job_type_id).name %></strong><br/><br/>
                            <p>Transaction Date:
                              <small><small><i><i class="fa fa-clock-o" aria-hidden="true"></i> <%= transaction.trans_date %></i></small></small>
                            </p>
                            <p>Paid to:
                              <% teen_lname = Teenager.find(transaction.teenager_id).lastname %>
                              <% teen_fname = Teenager.find(transaction.teenager_id).firstname %>
                              <% teen_lname ||= "NoLastname" %>
                              <% teen_fname ||= "NoFirstname" %>
                              <% teen_name = teen_lname + ", " + teen_fname %>
                              <small><%= teen_name %></small>
                            </p>
                            <p>Amount:
                              <small><%= number_to_currency(transaction.amount) %></small>
                            </p>
                            <p>Status:
                              <small><%= transaction.status %></small>
                            </p>
                        </div>
                        <div>
                            <div class="pull-right btn-group-xs">
                                <%= link_to(user_transaction_path(current_user.id, transaction.id)) do %>
                                  <div class="btn btn-default btn-xs"><i class="fa fa-info-circle" aria-hidden="true"></i> More info...</div>
                                <% end %>
                            </div><br>
                        </div>
                        <hr>
                      <% end %>
                    <% end %>


                </div>
            </div>
        </div>




        <div class="col-lg-3 col-md-3 hidden-sm hidden-xs">
            <div class="panel panel-default">

                <div class="panel-body">
                    <div class="media">
                        <div align="center">
                            <img class="thumbnail img-responsive" src="https://res.cloudinary.com/closebrace/image/upload/w_400/v1491315007/usericon_id76rb.png" width="300px" height="300px">
                        </div>
                        <div class="media-body">
                            <hr>
                            <span class="pull-right">
                                <div class="btn btn-link" style="text-decoration:none;">
                                    <%= link_to(edit_user_client_path(@user.id, @client.id)) do %>
                                        <i class="fa fa-lg fa-gear" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="Mention"></i>
                                    <% end %>
                                </div>
                            </span>
                            <h3>Bio</h3>
                            <p>Usertype: Client </p>
                            <p>Gender: <%= @client.gender%></p>
                            <p>Birthday (mm/dd/yyyy): <%= @client.birth_month %>/<%= @client.birth_day %>/<%= @client.birth_year %></p>
                            <hr>
                            <h3><strong>Primary Address</strong></h3>
                            <p>Street: <%= @client.address%></p>
                            <p>Apartment number: <%= @client.apt_no%></p>
                            <p>City: <%= @client.city%></p>
                            <p>Province: <%= @client.province%></p>
                            <p>Country: <%= @client.country%></p>
                            <p>Postal Code: <%= @client.postal_code%></p>
                            <hr>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/template/profile/_scr_search_form.html.erb
<div class="box">

<%= form_with(local: true) do |form| %>


  <h1>Search a teenager or a client</h1>
  <div class="col-half">
    <p>
      <%= form.label :'First Name:' %>
      <%= form.text_field :firstname %>
    </p>
  </div>
  <div class="col-half">
    <p>
      <%= form.label :'Last Name:' %>
      <%= form.text_field :lastname %>
    </p>
  </div>
  <div class="row">
  <div class="col-half">
  <p>
  <h3>
    <%= form.label :'Type:' %>
  </h3>
    <%= form.select :type, [['Teenager', '0'], ['Client', '1']] %>
 
  </p>
  </div>
</div>
  <h3>Date of Birth</h3>
  <p>
  <div class="col-third">
    <%= form.label :'Month' %>
    <%= form.text_field :birth_month %>
  </div>
  <div class="col-third">
    <%= form.label :'Day' %>
    <%= form.text_field :birth_day %>
  </div>
  <div class="col-third">
    <%= form.label :'Year' %>
    <%= form.text_field :birth_year %>
  </div>
  </p>

  <h3>Address</h3>
    <p>
    <%= form.label :'Address Line' %>
    <%= form.text_field :address %>
  </p>
  <p>
    <%= form.label :'Apt.No' %>
    <%= form.text_field :apt_no %>
  </p>
    <p>
    <%= form.label :'City' %>
    <%= form.text_field :city %>
  </p>
  <div class="col-half">
  <p>
    <%= form.label :'Province/State' %>
    <%= form.text_field :province %>
  </p>
  </div>
  <div class="col-half">
  <p>
    <%= form.label :'Country' %>
    <%= form.text_field :country %>
  </p>
  </div>
  <p>
    <%= form.label :'Postal Code' %>
    <%= form.text_field :postal_code %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

</div>