prj/config/routes.rb
Rails.application.routes.draw do

  # ROOT
  root 'home#index'

  # Registration Devise Route
  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}

  # Home Routes
  get 'home/index'
  get 'welcome/index'

  # Search Routes
  get 'search', to: 'search#search', as: 'search'
  get 'job_types/index', to: 'job_types#index', as: 'job_types'
  # JOB Routes
  resources :jobs
  resources :job_types
  resources :offer_jobs
  resources :apply_jobs
  resources :accept_jobs
  resources :cancel_jobs
  resources :finished_jobs
  get 'my_finished_jobs', to: 'finished_jobs#my_finished_jobs'
  get 'job/clientjobs', to: 'jobs#clientjobs', as: 'clientjobs'
  get 'job/:id/recommended_teens', to: 'jobs#recommended_teens', as: 'recommended_teens'
  get 'profile/:user_id', to: 'profiles#this_profile', as: 'this_profile'

  resources :charges
  resources :admin, only: [:index]

  # Routes
  resources :users, only: [:index, :show, :destroy] do
    resources :transactions
    resources :clients, only: [:show, :edit, :update]
    resources :endorsements, only: [:create, :update, :destroy]
    resources :teenagers, :name_prefix => "user_", only: [:show, :edit, :update]

	  get 'payments/index', to: 'payments#index', as: 'paymentsindex'

    member do
         post :pay
         post :subscribe
    end
  end

  resources :teenagers do
    resources :skills, :name_prefix => "teenager_"
  end

  get '/users/connect_stripe' => 'users#connect_stripe'

  resources :transactions

  # Stripe Connect endpoints
  #  - oauth flow
  get '/connect/oauth' => 'stripe#oauth', as: 'stripe_oauth'
  get '/connect/confirm' => 'stripe#confirm', as: 'stripe_confirm'
  get '/connect/deauthorize' => 'stripe#deauthorize', as: 'stripe_deauthorize'
  #  - create accounts
  post '/connect/managed' => 'stripe#managed', as: 'stripe_managed'
  post '/connect/standalone' => 'stripe#standalone', as: 'stripe_standalone'

  # Stripe webhooks
  post '/hooks/stripe' => 'hooks#stripe'
end

prj/app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
	def new
		@transaction = Transaction.new
		@user = current_user
		@users = User.all
		@clients = Client.all
		@teenagers = Teenager.all
		@jobs = Job.all
	end

	def edit
		@user = current_user
		@transaction = Transaction.find(params[:id])
	end

	def index
		@user = current_user
		@transactions = nil
		if @user.usertype == 0 # Teenager
			@teenager = Teenager.find_by(user_id: @user.id)
			@transactions = Transaction.where(teenager_id: @teenager.id).order(trans_date: :desc)
		else # Client
			@client = Client.find_by(user_id: @user.id)
			@transactions = Transaction.where(client_id: @client.id).order(trans_date: :desc)
		end
	end

	def create
		Transaction.create!(:teenager_id => params[:transaction][:teenager_id],
												:client_id => params[:transaction][:client_id],
												:job_id => params[:transaction][:job_id],
												:amount => params[:transaction][:amount],
												:trans_date => params[:transaction][:trans_date],
												:status => params[:transaction][:status],)
		# Transaction.create!(:teenager_id => 5,
		# 										:client_id => 7,
		# 										:job_id => 1,
		# 										:amount => 100,
		# 										:trans_date => rand_time(2.days.ago),
		# 										:status => 'done',)
		redirect_to controller: 'transactions', action: 'index', user: params[:user]
	end

	def show
		@user = current_user
		@transaction = nil
		@type = nil
		if @user.usertype == 0 # Teenager
			teenager = Teenager.find(user_id: current_user.id)
			@type = teenager
			@transaction = Transaction.find(params[:id])
		else # Client
			client = Client.find_by(user_id: current_user.id)
			@type = client
			@transaction = Transaction.find(params[:id])
		end
	end

	def mytransaction
		@user = User.find(params[:user])
		@jobs = Transaction.where(:teenager_id => params[:user]).all
	end

	private
	def transaction_params
		params.require(:transaction).permit(:teeanger_id, :client_id, :job_id, :amount, :trans_date, :status)
	end

	def rand_time(from, to=Time.now)
	  Time.at(rand_in_range(from.to_f, to.to_f))
	end

	def rand_in_range(from, to)
	  rand * (to - from) + from
	end
end

prj/app/views/template/display/_admin_console.html.erb
<div class="container">
	<div class="row">
		<section class="content">
			<h1>Admin Console</h1>
			<div class="col-md-8 col-md-offset-2">
				<div class="panel panel-default">
					<div class="panel-body">
						<div class="table-container">
							<table id="admin_table" class="table table-filter">
								<tbody>
									<% if @jobs %>
 										<% @jobs.each do |job| %>
	 										<tr data-status="jobs" data-link="<%= job_path(job.id) %>">
												<td>
													<div class="media">
														<div class="media-body">
															<span class="media-meta pull-right">Created at: <%= job.created_at %></span>
															<h4 class="title">
																<%= link_to(job_path(job)) do %>
																	Job Type: <%= JobType.find(job.job_type_id).name %>
																<% end %>
															</h4>
															<% client_lname = Client.find(job.client_id).lName %>
					                    <% client_fname = Client.find(job.client_id).fName %>
					                    <% client_lname ||= "NoLastname" %>
					                    <% client_fname ||= "NoFirstname" %>
					                    <% client_name = client_lname + ", " + client_fname %>
															<h5>Offered By: <%= client_name %></h5>
															<p><b>Start Time:</b> <%= job.starttime %> <b>Finish Time:</b> <%= job.finishtime %> <b>For a total of</b> <%= job.hours %> hours </p>
															<p class="summary"><b>Brief Summary:</b> <%= job.description %></p>
															<span class="media-meta pull-right">
															<%= link_to "Edit", :controller => :jobs, :action => :edit, :id => job.id %>
															</span>
														</div>
													</div>
												</td>
											</tr>
										<% end %>
									<% end %>
									<% if @users %>
 										<% @users.each do |user| %>
											<tr data-status="users" data-link="<%= this_profile_path(user.id) %>">
												<td>
													<div class="media">
														<div class="media-body">
															<span class="media-meta pull-right">Created at: <%= user.created_at %></span>
															<h4 class="title">
																	ID: <%= user.id %>
																	<% if user.usertype == 0 %>
																		Usertype: Teen<br>
																	<% elsif user.usertype == 1 %>
																		Usertype: Client<br>
																	<% else %>
																	 	Usertype: Admin
																	<% end %>
															</h4>
															<p><b>Username:</b> <%= user.username %></p>
															<span class="media-meta pull-right">
															<% if user.usertype == 0 %>
															<%= link_to "Edit", :controller => :teenagers, :action => :edit, :user_id => user.id, :id => user.teenager.id %>
															<!--%= link_to Destroy, user_path(user), method: :delete, data: { confirm: Are you sure? } %> -->
															<% elsif user.usertype == 1 %>
															<%= link_to "Edit", :controller => :clients, :action => :edit, :user_id => user.id, :id => user.client.id %>
															<% end %>
															</span>
														</div>
													</div>
												</td>
											</tr>
										<% end %>
									<% end %>
									<% if @transactions %>
 										<% @transactions.each do |transaction| %>
											<tr data-status="transactions" data-link="<%= transaction_path(transaction.id) %>">
												<td>
													<div class="media">
														<div class="media-body">
															<span class="media-meta pull-right">Created at: <%= transaction.created_at %></span>
															<h4 class="title">
																	ID: <%= transaction.id %>
															</h4>
															<% client_lname = Client.find(transaction.client_id).lName %>
					                    <% client_fname = Client.find(transaction.client_id).fName %>
					                    <% client_lname ||= "NoLastname" %>
					                    <% client_fname ||= "NoFirstname" %>
					                    <% client_name = client_lname + ", " + client_fname %>
															<% teen_lname = Teenager.find(transaction.teenager_id).lastname %>
				                      <% teen_fname = Teenager.find(transaction.teenager_id).firstname %>
				                      <% teen_lname ||= "NoLastname" %>
				                      <% teen_fname ||= "NoFirstname" %>
				                      <% teen_name = teen_lname + ", " + teen_fname %>
															<p><b>From:</b> <%= client_name %> <b>To:</b> <%= teen_name %></br>
																<b>At:</b> <%= transaction.trans_date %> <b>For:</b> <%= number_to_currency(transaction.amount) %></p>
															<span class="media-meta pull-right">
															<%= link_to "Edit", edit_transaction_path(transaction.id) %>
															</span>
														</div>
													</div>
												</td>
											</tr>
										<% end %>
									<% end %>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
			<div class="col-sm-3 col-md-2 well">
				<span>
					<button type="button" class="btn btn-primary btn-filter" data-target="users">All Users</button>
					<hr>
					<button type="button" class="btn btn-primary btn-filter" data-target="jobs">All Jobs</button>
					<hr>
					<button type="button" class="btn btn-primary btn-filter" data-target="transactions">All Transactions</button>
				</span>
			</div>

			<script>
				$("tr[data-link]").click(function() {
					window.location = $(this).data("link")
				})
			</script>

		</section>
	</div>
</div>

prj/app/views/transactions/_edit_transaction.html.erb
<div class="box">
  <%= form_with(model: @transaction, local: true) do |form| %>
    <% if @transaction.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@transaction.errors.count, "error") %>
          prohibited this client form from being saved:
        </h2>
        <ul>
          <% @transaction.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <h1>Edit Transaction</h1>
    <div class="row">
      <div class="col-third">
        <p>Transaction ID: <%= @transaction.id %></p>
      </div>
    </div>

    <div class="row">
      <p>
        <div class="col-half">
          <% client_lname = Client.find(@transaction.client_id).lName %>
          <% client_fname = Client.find(@transaction.client_id).fName %>
          <% client_lname ||= "NoLastname" %>
          <% client_fname ||= "NoFirstname" %>
          <% client_name = client_lname + ", " + client_fname %>
          <label>Client: (<%= client_name %>)</label>
          <%= form.number_field :client %>
        </div>
        <div class="col-half">
          <% teen_lname = Teenager.find(@transaction.teenager_id).lastname %>
          <% teen_fname = Teenager.find(@transaction.teenager_id).firstname %>
          <% teen_lname ||= "NoLastname" %>
          <% teen_fname ||= "NoFirstname" %>
          <% teen_name = teen_lname + ", " + teen_fname %>
          <label>Teenager: (<%= teen_name %>)</label>
          <%= form.number_field :teenager %>
        </div>
      </p>
    </div>

    <div class="row">
      <br/>
      <p>
        <label>DateTime: <%= @transaction.trans_date %></label>
        <%= form.datetime_local_field :trans_date %>
      </p>
    </div>

    <div class="row">
      <p>
        <div class="col-half">
          <label>Amount: (<%= @transaction.amount %>)</label>
          <%= form.number_field :amount %>
        </div>
        <div class="col-half">
          <label>Status: <%= @transaction.status %></label>
          <%= form.text_field :status %>
        </div>
      </p>
    </div>

    <div class="row">
      <br/>
      <p>
        <%= form.submit %>
      </p>
    </div>

  <% end %>

</div>

prj/app/views/transactions/_transaction_info.html.erb
<body>
  <div class="container" style="padding-top:55px;">
    <div class="row">
      <section class="content">
        <div class="col-md-6 col-md-offset-3">
          <div class="panel panel-default">
            <div class="panel-body">
              <div class="col-md-12 divider text-center"></div>
              <div class="col-md-10 col-md-offset-1" style="padding-top: 10px">
                <div class="col-md-12 text-left">
                  <p><strong>Transaction ID: </strong><%= @transaction.id %></p>
                  <p>Job Type: <%= JobType.find(@transaction.job.job_type_id).name %></p>
                  <p>Description: <%= @transaction.job.description %></p>
                  <% client_lname = Client.find(@transaction.client_id).lName %>
                  <% client_fname = Client.find(@transaction.client_id).fName %>
                  <% client_lname ||= "NoLastname" %>
                  <% client_fname ||= "NoFirstname" %>
                  <% client_name = client_lname + ", " + client_fname %>
                  <p>Client: <%= client_name %></p>
                  <% teen_lname = Teenager.find(@transaction.teenager_id).lastname %>
                  <% teen_fname = Teenager.find(@transaction.teenager_id).firstname %>
                  <% teen_lname ||= "NoLastname" %>
                  <% teen_fname ||= "NoFirstname" %>
                  <% teen_name = teen_lname + ", " + teen_fname %>
                  <p>Teenager: <%= teen_name %></p>
                  <p>Transaction Date (mm/dd/yyyy): <%= @transaction.trans_date%></p>
                  <p>Amount: <%= number_to_currency(@transaction.amount) %></p>
                  <p>Status: <%= @transaction.status%></p>
                </div>
              </div>
              <div class="col-md-12 divider text-center"></div>
              <% if @type.nil? %>
              <% else %>
                <div class="col-md-12">
                  <row>
                    <div class="col-md-2 emphasis" style="padding: 5px">
                      <%= link_to(user_transactions_path(current_user.id, @type.id)) do %>
                        <button type="button" class="btn btn-primary btn-block"><span class="fa fa-list-ul">Prev</span></button>
                      <% end %>
                    </div>
                    <div class="col-md-2 emphasis" style="padding: 5px">
                      <%= link_to(user_transactions_path(current_user.id, @type.id)) do %>
                        <button type="button" class="btn btn-primary btn-block"><span class="fa fa-list-ul">Next</span></button>
                      <% end %>
                    </div>
                    <div class="col-md-2 emphasis col-md-offset-6" style="padding: 5px">
                      <%= link_to(user_transactions_path(current_user.id, @type.id)) do %>
                        <button type="button" class="btn btn-primary btn-block"><span class="fa fa-list-ul"></span></button>
                      <% end %>
                    </div>
                  </row>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</body>

<!-- enclosing tags -->

prj/app/views/transactions/edit.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1"> <!-- For MOBILE -->
<title>Profile</title>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
<%= stylesheet_link_tag 'sidebar' %>
<%= stylesheet_link_tag 'forms' %>
</head>

<body>
 <% if user_signed_in? %>
 	<%= render :partial => "edit_transaction" %>
	<%= render :partial => "template/nav/usermenu" %>
<% else %>

	<%= render :partial => "template/nav/defaultmenu" %>

<% end %>

</body>
<%= javascript_include_tag 'jquery' %>
<%= javascript_include_tag 'bootstrap.min' %>
<%= javascript_include_tag 'sidebar' %>
</html>

prj/app/views/users/payment_details.html.erb
<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>

<div class="box">
  <form>
    <div class="row">
      <h1> Payment Details </h1>
      <div class="input-group">
	<input type="radio" name="payment-method" value="visa" id="payment-method-visa" checked="true"/>
	<label for="payment-method-visa"><span>Visa</span></label>
	<input type="radio" name="payment-method" value="mastercard" id="payment-method-mastercard"/>
	<label for="payment-method-mastercard"><span>Mastercard</span></label>
	<input type="radio" name="payment-method" value="amex" id="payment-method-amex"/>
	<label for="payment-method-amex"><span>American Express</span></label>
      </div>
      <div class="input-group input-group-icon">
        <input type="text" placeholder="Card Number" maxlength="16"/>
        <div class="input-icon"><i class="material-icons">payment</i></div>
      </div>
	  <div class="col-half">
        <div class="input-group input-group-icon">
          <input type="text" placeholder="Card CVC" maxlength="3"/>
          <div class="input-icon"><i class="material-icons">person</i></div>
		</div>
	  </div>
      <div class="col-half">
        <div class="input-group">
          <select>
            <option>Jan</option>
            <option>Feb</option>
			<option>March</option>
			<option>April</option>
			<option>May</option>
			<option>June</option>
			<option>July</option>
			<option>Aug</option>
			<option>Sep</option>
			<option>Oct</option>
			<option>Nov</option>
			<option>Dec</option>
          </select>
		  <select>
			<option>2017</option>
			<option>2018</option>
			<option>2019</option>
			<option>2020</option>
			<option>2021</option>
		  </select>
		</div>
	  </div>
	</div>
  </form>

    <div class="row">
      <h4>Terms and Conditions</h4>
      <div class="input-group">
        <input type="checkbox" id="terms"/>
        <label for="terms"><span>I accept the terms and conditions for signing up to this service, and hereby confirm I have read the privacy policy.</span></label>
	</div>
	</div>

	<a href="http://localhost:3000/welcome" class="myButton pull-right">Continue</a>
</div>