config/routes.rb
Rails.application.routes.draw do

  # ROOT
  root 'home#index'

  # Registration Devise Route
  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}

  # Home Routes
  get 'home/index'
  get 'welcome/index'

  # Search Routes
  get 'search', to: 'search#search', as: 'search'
  get 'job_types/index', to: 'job_types#index', as: 'job_types'
  # JOB Routes
  resources :jobs
  resources :job_types
  resources :offer_jobs
  resources :apply_jobs
  resources :accept_jobs
  resources :cancel_jobs
  resources :finished_jobs
  get 'my_finished_jobs', to: 'finished_jobs#my_finished_jobs'
  get 'job/clientjobs', to: 'jobs#clientjobs', as: 'clientjobs'
  get 'job/:id/recommended_teens', to: 'jobs#recommended_teens', as: 'recommended_teens'
  get 'profile/:user_id', to: 'profiles#this_profile', as: 'this_profile'

  resources :charges
  resources :admin, only: [:index]

  # Routes
  resources :users, only: [:index, :show, :destroy] do
    resources :transactions
    resources :clients, only: [:show, :edit, :update]
    resources :endorsements, only: [:create, :update, :destroy]
    resources :teenagers, :name_prefix => "user_", only: [:show, :edit, :update]

	  get 'payments/index', to: 'payments#index', as: 'paymentsindex'

    member do
         post :pay
         post :subscribe
    end
  end

  resources :teenagers do
    resources :skills, :name_prefix => "teenager_"
  end

  get '/users/connect_stripe' => 'users#connect_stripe' 

  # Stripe Connect endpoints
  #  - oauth flow
  get '/connect/oauth' => 'stripe#oauth', as: 'stripe_oauth'
  get '/connect/confirm' => 'stripe#confirm', as: 'stripe_confirm'
  get '/connect/deauthorize' => 'stripe#deauthorize', as: 'stripe_deauthorize'
  #  - create accounts
  post '/connect/managed' => 'stripe#managed', as: 'stripe_managed'
  post '/connect/standalone' => 'stripe#standalone', as: 'stripe_standalone'

  # Stripe webhooks
  post '/hooks/stripe' => 'hooks#stripe'
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
	def new
		@transaction = Transaction.new
		@user = current_user
		@users = User.all
		@clients = Client.all
		@teenagers = Teenager.all
		@jobs = Job.all
	end

	def index
		@user = current_user
		@transactions = nil
		if @user.usertype == 0 # Teenager
			@teenager = Teenager.find_by(user_id: @user.id)
			@transactions = Transaction.where(teenager_id: @teenager.id).order(trans_date: :desc)
		else # Client
			@client = Client.find_by(user_id: @user.id)
			@transactions = Transaction.where(client_id: @client.id).order(trans_date: :desc)
		end
	end

	def create
		# Transaction.create!(:teenager_id => params[:transaction][:teenager_id],
		# 										:client_id => params[:transaction][:client_id],
		# 										:job_id => params[:transaction][:job_id],
		# 										:amount => params[:transaction][:amount],
		# 										:trans_date => params[:transaction][:trans_date],
		# 										:status => params[:transaction][:status],)
		Transaction.create!(:teenager_id => 5,
												:client_id => 7,
												:job_id => 1,
												:amount => 100,
												:trans_date => rand_time(2.days.ago),
												:status => 'done',)
		redirect_to controller: 'transactions', action: 'index', user: params[:user]
	end

	def show
		@user = current_user
		@transaction = nil
		@type = nil
		if @user.usertype == 0 # Teenager
			teenager = Teenager.find(user_id: current_user.id)
			@type = teenager
			@transaction = Transaction.find(params[:id])
		else # Client
			client = Client.find_by(user_id: current_user.id)
			@type = client
			@transaction = Transaction.find(params[:id])
		end
	end

	def mytransaction
		@user = User.find(params[:user])
		@jobs = Transaction.where(:teenager_id => params[:user]).all
	end

	private
	def transaction_params
		params.require(:transaction).permit(:teeanger_id, :client_id, :job_id, :amount, :trans_date, :status)
	end

	def rand_time(from, to=Time.now)
	  Time.at(rand_in_range(from.to_f, to.to_f))
	end

	def rand_in_range(from, to)
	  rand * (to - from) + from
	end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_transaction_board.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h4>Transaction board</h4>

      <div class="table-responsive">
        <% if @transactions.nil? %>
          <strong>No transactions found</strong>
        <% elsif Array(@transactions).count == 0 %>
          <strong>No transactions found</strong>
        <% else %>
          <h5>Show
            <div class="form-group" style="display: inline-block;">
              <select name="state" id="trans_maxRows" class="form-control" style="width: 70px;">
              <option value="10">10</option>
              <option value="15">15</option>
              <option value="20">20</option>
              <option value="50">50</option>
              <option value="100">100</option>
              </select>
            </div>
          entries
          </h5>

          <table id="trans_table" class="table table-bordred table-striped">
            <thead>
              <th>Date</th>
              <th>Client</th>
              <th>Teenager</th>
              <th>Job</th>
              <th>Payment</th>
              <th>Amount</th>
              <th>Status</th>
            </thead>
            <tbody>
              <% Array(@transactions).each do |transaction| %>
                <tr>
                  <td><%= transaction.trans_date %></td>
                  <% client_lname = Client.find(transaction.client_id).lName %>
                  <% client_fname = Client.find(transaction.client_id).fName %>
                  <% client_lname ||= "NoLastname" %>
                  <% client_fname ||= "NoFirstname" %>
                  <% client_name = client_lname + ", " + client_fname %>
                  <td><%= client_name %></td>
                  <% if transaction.teenager_id == nil %>
                    <td>Error: teenager_id==nil, name cannot be retrieved</td>
                  <% else %>
                    <% teen_lname = Teenager.find(transaction.teenager_id).lastname %>
                    <% teen_fname = Teenager.find(transaction.teenager_id).firstname %>
                    <% teen_lname ||= "NoLastname" %>
                    <% teen_fname ||= "NoFirstname" %>
                    <% teen_name = teen_lname + ", " + teen_fname %>
                    <td><%= teen_name %></td>
                  <% end %>
                  <td><%= JobType.find(transaction.job.job_type_id).name %></td>
                  <td>TBD</td>
                  <td><%= transaction.amount %></td>
                  <td><%= transaction.status %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <div class="clearfix"></div>

          <div class="pagination-container">
        		<nav>
        			<ul class="pagination pull-right"></ul>
        		</nav>
      	  </div>

          <script>
            var table = '#trans_table'
            $('#trans_maxRows').on('change', function () {
              $('.pagination').html('')
              var trnum = 0
              var maxRows = parseInt($(this).val())
              var totalRows = $(table + ' tbody tr').length
              $(table + ' tr:gt(0)').each(function () {
                trnum++
                if (trnum > maxRows) {
                  $(this).hide()
                }
                if (trnum <= maxRows) {
                  $(this).show()
                }
              })
              if (totalRows > maxRows) {
                var pagenum = Math.ceil(totalRows / maxRows)
                for (var i = 1; i <= pagenum;) {
                  $('.pagination').append('<li data-page="' + i + '">\<span>' + i++ + '<span class="sr-only">(current)</span></span>\</li>').show()
                }
              }
              $('.pagination li:first-child').addClass('active')
              $('.pagination li').on('click', function () {
                var pagenum = $(this).attr('data-page')
                var trIndex = 0;
                $('.pagination li').removeClass('active')
                $(this).addClass('active')
                $(table + ' tr:gt(0)').each(function () {
                  trIndex++
                  if (trIndex > (maxRows * pagenum) || trIndex <= ((maxRows * pagenum) - maxRows)) {
                    $(this).hide()
                  } else {
                    $(this).show()
                  }
                })
              })
            })

            $(function () {
              $('table tr:eq(0)').prepend('<th>ID</th>')
              var id = 0;
              $('table tr:gt(0)').each(function () {
                id++
                $(this).prepend('<td>' + id + '</td>')
              })
            })
            $('#trans_maxRows').trigger("change");
          </script>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/transactions/_transaction_info.html.erb
<body>
  <div class="container" style="padding-top:55px;">
    <div class="well profile">
      <div class="col-md-12 col-md-offset-2">
          <div class="col-md-12 divider text-center"></div>
	    	  <div class="col-md-12" style="padding-top: 10px">
            <div class="col-md-6 text-left">
    					<p><strong>Transaction ID: </strong><%= @transaction.id %></p>
    					<p>Job Type: <%= JobType.find(@transaction.job.job_type_id).name %></p>
    					<p>Description: <%= @transaction.job.description %></p>
              <% client_lname = Client.find(@transaction.client_id).lName %>
              <% client_fname = Client.find(@transaction.client_id).fName %>
              <% client_lname ||= "NoLastname" %>
              <% client_fname ||= "NoFirstname" %>
              <% client_name = client_lname + ", " + client_fname %>
              <p>Client: <%= client_name %></p>
              <% teen_lname = Teenager.find(@transaction.teenager_id).lastname %>
              <% teen_fname = Teenager.find(@transaction.teenager_id).firstname %>
              <% teen_lname ||= "NoLastname" %>
              <% teen_fname ||= "NoFirstname" %>
              <% teen_name = teen_lname + ", " + teen_fname %>
              <p>Teenager: <%= teen_name %></p>
    					<p>Transaction Date (mm/dd/yyyy): <%= @transaction.trans_date%></p>
    					<p>Amount: <%= number_to_currency(@transaction.amount) %></p>
    					<p>Status: <%= @transaction.status%></p>
            </div>
	    	  </div>

	    	  <div class="col-md-12 divider text-center">
            <row>
	        		<div class="col-md-1 emphasis" style="padding: 5px">
	        			<%= link_to(user_transactions_path(current_user.id, @type.id)) do %>
	        				<button type="button" class="btn btn-primary btn-block"><span class="fa fa-list-ul"></span></button>
	        			<% end %>
	        		</div>
	        	</row>
	        </div>
        </div>
	   </div>
  </div>
</body>

<!-- enclosing tags -->

app/views/transactions/_transactions_form.html.erb
<%= form_with(model: [@user, @transaction], local: true) do |form| %>

  <p>
    <%= form.label :'Teen ID:' %>
    <%= form.text_field :teenager_id %>
  </p>
    <p>
    <%= form.label :'Client ID:' %>
    <%= form.text_field :client_id %>
  </p>
      <p>
    <%= form.label :'Job ID:' %>
    <%= form.text_field :job_id %>
  </p>
  <p>
    <%= form.label :'Amount:' %>
    <%= form.number_field :amount %>
  </p>
  <p>
    <%= form.label :'Trans_Date:' %>
    <%= form.datetime_local_field :trans_date %>
  </p>
  <p>
    <%= form.label :'Status:' %>
    <%= form.text_field :status %>
  </p>
  <p>
  	<%= form.submit %>
  </p>
<% end %>

app/views/transactions/edit.html.erb
<h1>Edit Transaction</h1>
 
<%= render 'transactions_form' %>

<%= link_to 'Back', user_transactions_path %>

app/views/transactions/index.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- For MOBILE -->
		<title>Transactions</title>

		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
		<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
		<%= stylesheet_link_tag 'sidebar' %>
	</head>

	<body>
		<% if user_signed_in? %>
			<%= render :partial => "template/nav/usermenu" %>
		<% else %>
			<%= render :partial => "template/nav/defaultmenu" %>
		<% end %>

		<%= render :partial => "transaction_board" %>

		<%= link_to 'Add Transaction', new_user_transaction_path %>
	</body>

	<%= javascript_include_tag 'jquery' %>
	<%= javascript_include_tag 'bootstrap.min' %>
	<%= javascript_include_tag 'sidebar' %>
</html>

app/views/transactions/mytransactions.html.erb
<h1>Transactions for</h1>
<p>
  <strong><%= @user.username %></strong>
</p>

<%= link_to 'Back', users_path(:user => @user.id) %>
<table>
  <tr>
    <th colspan="1"></th>
  </tr>
 
  <% @transactions.each do |transaction| %>
    <tr>
      <td><%= transaction.teenager_id %></td>
      <td><%= transaction.client_id %></td>
      <td><%= transaction.job_id %></td>
      <td><%= transaction.payment_id %></td>
      <td><%= link_to 'Show', transaction_path %></td>
      <td><%= link_to 'Edit', edit_transaction_path %></td>
      <td><%= link_to 'Destroy', transaction_path,
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <br />
</table>
      


    </tr>
  <% end %>
</table>

app/views/transactions/new.html.erb
<h1>Add Transactions</h1>

<%= render 'transactions_form' %>

<%= link_to 'Back', user_transactions_path(@user.id) %>

<h1>Users</h1>
<table>
  <tr>
    <th>Username</th>
    <th>User_type</th>
    <th>User_id</th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <% if user.usertype == 0 %>
        <td>Teen (0)</td>
        <% elsif user.usertype == 1 %>
          <td>Client (1)</td>
        <% else %>
          <%= user.usertype %>
        <% end %>
        <td><%= user.id %></td>
      </tr>
    <% end %>
  </table>

  <h1>Clients</h1>
  <table>
    <tr>
      <th>First_Name</th>
      <th>Last_Name</th>
      <th>client_id</th>
    </tr>

    <% @clients.each do |client| %>
      <tr>
        <td><%= client.fName %></td>
        <td><%= client.lName %></td>
        <td><%= client.id %></td>
      </tr>
    <% end %>
  </table>

  <h1>Teenagers</h1>
  <table>
  	<tr>
  		<th>First_Name</th>
  		<th>Last_Name</th>
      <th>teenager_id</th>
  	</tr>

  	<% @teenagers.each do |teenager| %>
  		<tr>
  		  <td><%= teenager.firstname %></td>
  		  <td><%= teenager.lastname %></td>
  		  <td><%= teenager.id %></td>
  		</tr>
  	<% end %>
  </table>

  <h1>Jobs</h1>
  <table>
  	<tr>
  		<th>job_id</th>
  	</tr>

  	<% @jobs.each do |job| %>
  		<tr>
  		  <td><%= job.id %></td>
  		</tr>
  	<% end %>
  </table>

app/views/transactions/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- For MOBILE -->
    <title>My Jobs</title>

    <!-- IMPORTANT ONLY WORKS FOR version < 3.3.1 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    <%= stylesheet_link_tag 'sidebar' %>
    <%= stylesheet_link_tag 'profile' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render :partial => "transaction_info" %>
      <%= render :partial => "template/nav/usermenu" %>
    <% end %>
  </body>

  <%= javascript_include_tag 'jquery' %>
  <%= javascript_include_tag 'bootstrap.min' %>
  <%= javascript_include_tag 'sidebar' %>

</html>